#!/bin/python3

import math
import os
import random
import re
import sys



#
# Complete the 'getTotalGoals' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. STRING team
#  2. INTEGER year
#
import requests
def getTotalGoals(team, year):
    url="https://jsonmock.hackerrank.com/api/football_matches?year="+str(year)+"&team1="+str(team)
    response1=requests.get(url)
    result1=response1.json()
    url2="https://jsonmock.hackerrank.com/api/football_matches?year="+str(year)+"&team2="+str(team)
    response2=requests.get(url2)
    result2=response2.json()
    ans=0
    for i in range(1,int(result1['total_pages'])+1):
        temp_url="https://jsonmock.hackerrank.com/api/football_matches?year="+str(year)+"&team1="+str(team)+"&page="+str(i)
        temp_response=requests.get(temp_url)
        temp_result=temp_response.json()
        for j in temp_result['data']:
            ans+=int(j['team1goals'])
    for i in range(1,int(result2['total_pages'])+1):
        temp_url2="https://jsonmock.hackerrank.com/api/football_matches?year="+str(year)+"&team2="+str(team)+"&page="+str(i)
        temp_response2=requests.get(temp_url2)
        temp_result2=temp_response2.json()
        for j in temp_result2['data']:
            ans+=int(j['team2goals'])
    return ans

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    team = input()

    year = int(input().strip())

    result = getTotalGoals(team, year)

    fptr.write(str(result) + '\n')

    fptr.close()
